### ISSUE TITLE
Decouple websocketpp from the rest of the program

### ISSUE THREAD

**Issue by ctrlaltf2** [ctrlaltf2/lets-play#44]
This is a step towards (#35).

**Comment by ctrlaltf2** [comment]
See https://github.com/ctrlaltf2/lets-play/tree/abstract-network

**Comment by modeco80** [comment]
Call me stupid but I'd use CRTP for this since there's not really any scenario where you have to switch at runtime unless for cases you could write into the transport

something ala
https://godbolt.org/z/cKP659
