### ISSUE TITLE
Replace JSON & HTTP parts

### ISSUE THREAD

**Issue by ctrlaltf2** [ctrlaltf2/lets-play#46]
Pretty sure nlohmann::json is one of the culprits (other than boost of course) for the terrible build times. That, and this is faster by a long shot.
The HTTP server is currently pretty tied to websocketpp. Because not all transport methods also implement an HTTP server, its probably best we roll our own HTTP server instead of what's tacked onto websocketpp or similar. (#44).
[This library](https://github.com/matt-42/lithium) looks very promising. Probably should use this for the JSON & HTTP. Also has SQL database support (#40).

Other things:
https://github.com/h2o/h2o (HTTP)
RapidJSON

**Comment by modeco80** [comment]
Boost.JSON is a pretty good amount [faster](https://www.boost.org/doc/libs/1_75_0/libs/json/doc/html/json/benchmarks.html) than rapidjson even beating rapidjson's pool stuff, unfortunately it JUST got incubated into boost so it'll need to be a submodule until everyone is on 1.75.0
