### ISSUE TITLE
libretro <-> Rust interface

### ISSUE THREAD

**Issue by ctrlaltf2** [ctrlaltf2/lets-play#55]
libretro's interface is a C API. We'll need to map this into Rust as a Rust API, *probably* wrapping a bunch of things in `unsafe`.

**Comment by modeco80** [comment]
`libretro-sys` (as well as a rather more confusingly named `rust-libretro-sys`) both exist, however:
- libretro-sys hasn't been updated in about 6 years
- the other confusingly named one, while it is actually updated and uses bindgen to generate from the libretro headers, seems specifically tailored for core development, exclusively choosing not to provide apis for linking to cores (well, to be fair, libretro-sys only provides a struct with function pointers that isn't filled in automatically at all, but it's better than nothing).

It might be worth just having our own -sys package generated with bindgen, as it does support that usecase (and will generate a struct that can simply be populated with all the functions just by a ::new() if configured to), and then wrapping that with a higher level binding

**Comment by ctrlaltf2** [comment]
Honestly `rust-libretro-sys` might do what we want. Cores are dynamically loaded at runtime (e.g. by `dlopen`) instead of being linked against in any way. It looks like that crate exports the info needed about the "shape" of the libretro data types and function calls- no needing to manually write all those.

**Comment by modeco80** [comment]
By "linking" I mean bindgen uses the `libloading` crate to do effectively the dlopen(), and the dlsym() of all the symbols just by ::new()'ing a struct that has all the function pointers, with a path to the library.

**Comment by modeco80** [comment]
nvm, actually looking at it, bindgen requires hardcoding the library name for some reason. Unofficial extensions to generate libloading bindings before it became a feature upstream *don't* make that same mistake, but they also don't work anymore.

I'll just use `libretro-sys` for now then, and figure something out if we end up wanting any fancy features that that crate doesn't bind (which basically just seems to be Vulkan support, so I don't really see that being a problem; most cores will probably target/can fall back to the retro hwcontext/opengl functions as needed)
